[project]
name = "packetllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hf-xet>=1.1.4",
    "sentencepiece>=0.2.0",
    "torch>=2.7.1",
    "transformers==4.39.0",
]
